[package]
name = "conways-game-of-life"
version = "0.0.1"
authors = ["Jake Marsden <jakemarsdenjm@gmail.com>"]
license = "MIT"
publish = false
edition = "2018"

[[bin]]
name = "conways-game-of-life"
path = "src/main.rs"

[dependencies]
structopt = "0.3"
